RPKM app that will work in pipeline
moka-guys/dnanexus_RPKM pull request #2
Opened 2017-04-03 08:39 UTC by aledj2

2017-05-24 12:47 UTC, woook requested changes
I've some queries - attached to lines in the readme

2017-05-24 12:47 UTC, woook commented on README.md
> +  * BAM files must be found in /output/
Is this correct? Is the output folder in the root of the project?

2017-05-24 12:47 UTC, woook commented on README.md
> +  * The RPKM bed file will have a different panel number (for +/-50bp) therefore the panel number which corresponds to the +/-10bp panel is required to download the relevant BAM files.
Why is the RPKM bed file different to the coverage bed file?

2017-05-24 12:47 UTC, woook commented on README.md
> +This app is based on the code in the github repo https://github.com/moka-guys/RPKM.
?
https://github.com/moka-guys/dnanexus_RPKM

2017-05-24 12:59 UTC, aledj2 commented on README.md
> +  * BAM files must be found in /output/
yes that's the path to the bam files. The dx download command ensures it's the non-deduplicated bams that are used.

2017-05-24 13:01 UTC, aledj2 commented on README.md
> +  * The RPKM bed file will have a different panel number (for +/-50bp) therefore the panel number which corresponds to the +/-10bp panel is required to download the relevant BAM files.
In moka there is entry in the gene panel table (which creates the Pannumber) for +/-10 and another for +/-50 which also details the control sites for CNV analysis.

2017-05-24 13:02 UTC, aledj2 commented on README.md
> +This app is based on the code in the github repo https://github.com/moka-guys/RPKM.
dnanexus_RPKM is this app. the RPKM code is in the repo stated above (so it can be run standalone)

2017-05-25 13:10 UTC, woook commented on README.md
> +  * BAM files must be found in /output/
As mentioned elsewhere - it makes no difference whether you use the BAMs straight from BWA or whether you use the _*duplicate-marked*_ BAMs

2017-05-25 13:11 UTC, woook commented on README.md
> +  * The RPKM bed file will have a different panel number (for +/-50bp) therefore the panel number which corresponds to the +/-10bp panel is required to download the relevant BAM files.
But why are we counting reads that fall outside the region of interest?

2017-05-25 13:11 UTC, woook submitted a review, later dismissed

2017-05-25 13:13 UTC, woook requested changes
See in-line comments

2017-05-25 13:16 UTC, aledj2 commented on README.md
> +  * BAM files must be found in /output/
Will add that to Readme

2017-05-25 13:18 UTC, aledj2 commented on README.md
> +  * The RPKM bed file will have a different panel number (for +/-50bp) therefore the panel number which corresponds to the +/-10bp panel is required to download the relevant BAM files.
That's what the scientists asked for...

2017-06-29 09:26 UTC, woook commented on README.md
> +
Please update readme in light of move to using one panel number for both coverage and CNV analysis.

2017-06-29 11:51 UTC, woook commented on src/code.sh
> +if (( $filecount < 6 )); then
Will RPKM generate solid number with just the reference samples? Do we / do we need to take into account the sex of the samples for X genes?

2017-06-30 14:23 UTC, woook approved these changes
Technically the code is ok but there are doubts regarding the validity of the output for CNV dosage quotient analysis.

2017-06-30 14:23 UTC, merged